/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-04 01:13:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ShippingInformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671504856282L));
    _jspx_dependants.put("jar:file:/C:/SPRING%20_wk/book/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/book/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	*{\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	#productinfo{\r\n");
      out.write("		margin-left: 150px;\r\n");
      out.write("		margin-right: 150px;\r\n");
      out.write("		display : flex;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	#DefaultAddr{\r\n");
      out.write("		margin-left: 150px;\r\n");
      out.write("		margin-right: 150px;\r\n");
      out.write("		display : flex;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	#productprice{\r\n");
      out.write("		margin-left: 600px;\r\n");
      out.write("		margin-right: 600px;\r\n");
      out.write("		display : flex;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		border: 1 solid;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#btn{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		display : flex;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../cart/cartheader.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<h2 style=\"text-align: center;\">\r\n");
      out.write("			주문상품정보\r\n");
      out.write("		</h2>\r\n");
      out.write("		\r\n");
      out.write("	<div id=\"productinfo\">\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>판매자정보</td>\r\n");
      out.write("				<td>제품정보</td>\r\n");
      out.write("				<td>가격정보</td>\r\n");
      out.write("				<td>수량</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<h2 style=\"text-align: center;\">배송지 정보 입력</h2>\r\n");
      out.write("		\r\n");
      out.write("	<form action=\"/cart/pay?mn=1\" method=\"post\">\r\n");
      out.write("	\r\n");
      out.write("		<div id=\"DefaultAddr\">\r\n");
      out.write("			<table id=\"Table1\" cellspacing=\"1\" cellpadding=\"3\" width=\"670\" bgcolor=\"#83b8c2\" border=\"0\" align=\"center\">\r\n");
      out.write("				<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td  bgcolor=\"#edf5fc\" style=\"padding-left:14px; text-align: left; width: 23%\"><span class=\"warning\">* </span>주문인</td>\r\n");
      out.write("					<td bgcolor=\"#ffffff\">\r\n");
      out.write("						<input type=\"text\" name=\"OrdererName\" class=\"form\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"20\" readonly=\"readonly\">\r\n");
      out.write("	 \r\n");
      out.write("						 휴대폰 번호 : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.mem_cell_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" <br>주문/배송에 관한 문자, 알림톡은 주문인 휴대전화번호로 발송되며,  <a style=\"color:#386da1\" href=\"#\" target=\"_blank\">개인정보수정 페이지</a>에서 변경 가능합니다.\r\n");
      out.write("					   \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#edf5fc\" style=\"padding-left:14px; text-align: left; width: 23%\"><span class=\"warning\">* </span>받으시는 분</td>\r\n");
      out.write("					<td bgcolor=\"#ffffff\"><input class=\"form\" type=\"text\" maxlength=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"ReceiverName\">\r\n");
      out.write("		 \r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#edf5fc\" style=\"padding-left:14px; text-align: left; width: 23%\"><span class=\"warning\">*</span>\r\n");
      out.write("						주 소</td>\r\n");
      out.write("					<td bgcolor=\"#ffffff\">\r\n");
      out.write("							<br>\r\n");
      out.write("							우편번호<input type=\"text\" id=\"Address1\" name=\"Address1\" class=\"form\" style=\"width:310px\" maxlength=\"100\" readonly=\"readonly\" value=\"\">\r\n");
      out.write("							<br>\r\n");
      out.write("							주소<input type=\"text\" id=\"Address1\" name=\"Address1\" class=\"form\" style=\"width:310px\" maxlength=\"100\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.mem_ad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							<br>\r\n");
      out.write("							추신<input type=\"text\" id=\"Address2\" name=\"Address2\" class=\"form\" style=\"width:310px\" maxlength=\"100\" value=\"\" placeholder=\"배송기사에게 남길말\">\r\n");
      out.write("				\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#edf5fc\" style=\"padding-left:14px; text-align: left; width: 23%\"><span class=\"warning\">* </span>휴대전화번호</td>\r\n");
      out.write("					<td bgcolor=\"#ffffff\">\r\n");
      out.write("					<input class=\"form\" type=\"text\" maxlength=\"10\" size=\"10\" name=\"Hp1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.mem_cell_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"> \r\n");
      out.write("					\r\n");
      out.write("			\r\n");
      out.write("						\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td bgcolor=\"#edf5fc\" style=\"padding-left:14px; text-align: left; width: 23%\">\r\n");
      out.write("						다른전화번호</td>\r\n");
      out.write("					<td bgcolor=\"#ffffff\">\r\n");
      out.write("					  <input class=\"form\" type=\"text\" maxlength=\"10\" size=\"10\" name=\"Tel3\" value=\"\"> (선택입력)</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</tbody></table>			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<button type=\"submit\" id=\"btn\" >상세결제페이지</button>\r\n");
      out.write("		\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/cart/ShippingInformation.jsp(69,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/cart/ShippingInformation.jsp(69,3) '${Clist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Clist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/cart/ShippingInformation.jsp(69,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("Clist");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<th>알라딘</td>\r\n");
            out.write("				<th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Clist.cart_book_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				<th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Clist.cart_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				<th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Clist.cart_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
